### ISSUE TITLE
Youtube Thumbnail Before Text

### ISSUE THREAD

**Issue by Teezton** [QuiteRSS/quiterss#1471]
On old versions the thumbnails as always the first thing to show up, now it's the description of the youtube channel, any way to change this:

![Image 002](https://user-images.githubusercontent.com/5905860/128007339-91afe0fe-3745-4563-8312-2d0c267c1aa7.png)

Into this?

![Image 001](https://user-images.githubusercontent.com/5905860/128007347-54db7581-1bd9-420c-b708-a326d1125d9b.png)

Nowadays, YouTubers write too much spam on the description of the video.
I tried to figure out how to do it testing a lot of code, but I can't find the code that makes the image display first than text. :(

**Comment by MatthaisUK** [comment]
Teezton asked for assistance with this on our CodeSupport Discord Server.  I tried the following styles in news.css:
```css
.newsTable tr:first-child > td {
  display: flex;
  flex-flow: column;
}

.newsTable tr:first-child > td > .description + img {
  order: -1;
}
```

However, while it works [within a JS Fiddle](https://jsfiddle.net/Matthais/yz031nkp/) (code copied from HTML saved from QuiteRSS), it seems as though whatever version of Webkit you're using in QuiteRSS isn't able to handle the flexbox, which I find quite alarming (along with the general use of tables for layout).
